#!/usr/bin/expect

# creds is a secret file defines USER and PASS
source creds

if { $::argc > 0 } {
#        spawn $::argv
	eval [list spawn -noecho] $::argv
        while { 1 } {
            expect {
		"Username for*: " {
			send "$USER\r"
		}
                eof {
			exit 0
		}
	    }
	    expect {
	        "Password for*: " {
			send "$PASS\r"
		}
 	 	eof {
			exit 0
		}
	    }
	}
} else {
	puts "usage desy-clone PRJ1..PRJ2"
}
